In [1]:
# dependencies
import pandas as pd
import os
import matplotlib

In [3]:
# File to Load 
file_to_load = "2017_PerformanceReports.csv"


# Read Purchasing File and store into Pandas data frame
performance_report = pd.read_csv(file_to_load)
performance_report.head(450)

,COUNTY_CODE,DISTRICT_CODE,SCHOOL_CODE,StudentGrowth,Expectations,LowGrowth,TypicalGrowth,HighGrowth
0,1,10,50,ELA,Did Not Yet Meet,3,1,2
1,1,10,50,ELA,Partially Met,2,4,5
2,1,10,50,ELA,Approached,12,4,8
3,1,10,50,ELA,Met,15,12,21
4,1,10,50,ELA,Exceeded,3,5,4
5,1,10,50,Math,Did Not Yet Meet,3,3,1
6,1,10,50,Math,Partially Met,6,6,4
7,1,10,50,Math,Approached,16,16,11
8,1,10,50,Math,Met,9,12,12
9,1,10,50,Math,Exceeded,0,1,1
10,1,10,60,ELA,Did Not Yet Meet,2,5,8
11,1,10,60,ELA,Partially Met,7,7,3
12,1,10,60,ELA,Approached,8,3,8
13,1,10,60,ELA,Met,31,10,5
14,1,10,60,ELA,Exceeded,2,0,0
15,1,10,60,Math,Did Not Yet Meet,0,2,2
16,1,10,60,Math,Partially Met,7,8,5
17,1,10,60,Math,Approached,8,12,15
18,1,10,60,Math,Met,14,10,14
19,1,10,60,Math,Exceeded,3,0,0
20,1,110,30,ELA,Did Not Yet Meet,3,6,5
21,1,110,30,ELA,Partially Met,4,8,10
22,1,110,30,ELA,Approached,8,11,14
23,1,110,30,ELA,Met,6,10,12
24,1,110,30,ELA,Exceeded,2,1,1
25,1,110,30,Math,Did Not Yet Meet,2,3,4
26,1,110,30,Math,Partially Met,10,7,10
27,1,110,30,Math,Approached,7,12,19
28,1,110,30,Math,Met,7,6,11
29,1,110,30,Math,Exceeded,2,0,1
...,...,...,...,...,...,...,...,...
420,1,4240,50,Math,Partially Met,2,2,8
421,1,4240,50,Math,Approached,15,13,15
422,1,4240,50,Math,Met,10,13,17
423,1,4240,50,Math,Exceeded,0,2,2
424,1,4800,50,ELA,Did Not Yet Meet,9,3,8
425,1,4800,50,ELA,Partially Met,5,7,5
426,1,4800,50,ELA,Approached,13,7,7
427,1,4800,50,ELA,Met,17,8,8
428,1,4800,50,ELA,Exceeded,0,1,0
429,1,4800,50,Math,Did Not Yet Meet,6,3,8
430,1,4800,50,Math,Partially Met,6,9,13
431,1,4800,50,Math,Approached,11,8,15
432,1,4800,50,Math,Met,8,4,7
433,1,4800,55,ELA,Did Not Yet Meet,6,5,4
434,1,4800,55,ELA,Partially Met,14,5,8
435,1,4800,55,ELA,Approached,7,7,10
436,1,4800,55,ELA,Met,13,8,9
437,1,4800,55,ELA,Exceeded,2,2,1
438,1,4800,55,Math,Did Not Yet Meet,4,4,4
439,1,4800,55,Math,Partially Met,13,10,16
440,1,4800,55,Math,Approached,11,8,4
441,1,4800,55,Math,Met,11,4,8
442,1,4800,55,Math,Exceeded,0,1,1
443,1,5350,40,ELA,Did Not Yet Meet,1,2,2
444,1,5350,40,ELA,Partially Met,4,6,7
445,1,5350,40,ELA,Approached,4,9,15
446,1,5350,40,ELA,Met,7,12,21
447,1,5350,40,ELA,Exceeded,3,2,2
448,1,5350,40,Math,Did Not Yet Meet,0,2,3
449,1,5350,40,Math,Partially Met,2,7,5

In [5]:
# remove all NaN values
performance_report.dropna(inplace=True)



# replace blank values with zeros
performance_report.replace('-', 0, inplace = True) 

print(performance_report.count())

COUNTY_CODE      16202
DISTRICT_CODE    16202
SCHOOL_CODE      16202
StudentGrowth    16202
Expectations     16202
LowGrowth        16202
TypicalGrowth    16202
HighGrowth       16202
dtype: int64

In [10]:
performance_report_df=pd.DataFrame(performance_report)
performance_report_df.rename(columns={"COUNTY_CODE": "County Code"},inplace=True)
performance_report_df.rename(columns={"DISTRICT_CODE": "District Code"},inplace=True)
performance_report_df.rename(columns={"SCHOOL_CODE": "School Code"},inplace=True)
performance_report_df

,County Code,District Code,School Code,StudentGrowth,Expectations,LowGrowth,TypicalGrowth,HighGrowth
0,1,10,50,ELA,Did Not Yet Meet,3,1,2
1,1,10,50,ELA,Partially Met,2,4,5
2,1,10,50,ELA,Approached,12,4,8
3,1,10,50,ELA,Met,15,12,21
4,1,10,50,ELA,Exceeded,3,5,4
5,1,10,50,Math,Did Not Yet Meet,3,3,1
6,1,10,50,Math,Partially Met,6,6,4
7,1,10,50,Math,Approached,16,16,11
8,1,10,50,Math,Met,9,12,12
9,1,10,50,Math,Exceeded,0,1,1
10,1,10,60,ELA,Did Not Yet Meet,2,5,8
11,1,10,60,ELA,Partially Met,7,7,3
12,1,10,60,ELA,Approached,8,3,8
13,1,10,60,ELA,Met,31,10,5
14,1,10,60,ELA,Exceeded,2,0,0
15,1,10,60,Math,Did Not Yet Meet,0,2,2
16,1,10,60,Math,Partially Met,7,8,5
17,1,10,60,Math,Approached,8,12,15
18,1,10,60,Math,Met,14,10,14
19,1,10,60,Math,Exceeded,3,0,0
20,1,110,30,ELA,Did Not Yet Meet,3,6,5
21,1,110,30,ELA,Partially Met,4,8,10
22,1,110,30,ELA,Approached,8,11,14
23,1,110,30,ELA,Met,6,10,12
24,1,110,30,ELA,Exceeded,2,1,1
25,1,110,30,Math,Did Not Yet Meet,2,3,4
26,1,110,30,Math,Partially Met,10,7,10
27,1,110,30,Math,Approached,7,12,19
28,1,110,30,Math,Met,7,6,11
29,1,110,30,Math,Exceeded,2,0,1
...,...,...,...,...,...,...,...,...
16172,80,8050,990,ELA,Did Not Yet Meet,0,1,0
16173,80,8050,990,ELA,Partially Met,8,3,7
16174,80,8050,990,ELA,Approached,7,4,7
16175,80,8050,990,ELA,Met,29,13,7
16176,80,8050,990,ELA,Exceeded,9,5,1
16177,80,8050,990,Math,Did Not Yet Meet,2,0,3
16178,80,8050,990,Math,Partially Met,10,2,7
16179,80,8050,990,Math,Approached,18,3,11
16180,80,8050,990,Math,Met,23,8,7
16181,80,8050,990,Math,Exceeded,5,2,0
16182,80,8065,980,ELA,Did Not Yet Meet,3,1,4
16183,80,8065,980,ELA,Partially Met,6,4,12
16184,80,8065,980,ELA,Approached,14,10,11
16185,80,8065,980,ELA,Met,10,10,12
16186,80,8065,980,ELA,Exceeded,1,1,1
16187,80,8065,980,Math,Did Not Yet Meet,4,0,4
16188,80,8065,980,Math,Partially Met,12,8,7
16189,80,8065,980,Math,Approached,21,7,7
16190,80,8065,980,Math,Met,15,8,5
16191,80,8065,980,Math,Exceeded,0,1,0
16192,80,8140,990,ELA,Did Not Yet Meet,2,3,8
16193,80,8140,990,ELA,Partially Met,7,8,12
16194,80,8140,990,ELA,Approached,8,11,11
16195,80,8140,990,ELA,Met,10,5,12
16196,80,8140,990,ELA,Exceeded,1,0,2
16197,80,8140,990,Math,Did Not Yet Meet,6,7,3
16198,80,8140,990,Math,Partially Met,11,12,12
16199,80,8140,990,Math,Approached,12,7,6
16200,80,8140,990,Math,Met,13,5,2
16201,80,8140,990,Math,Exceeded,3,0,1

In [17]:
performance_report_df.to_csv("CLEAN_PERFORMANCE_REPORT_DATA.csv")